name: Lint C code

on: [push]

jobs:
  run-c-linter:
    name: Run C linter
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Build the ledger docker image
        run: docker/ledger/build

      - name: Lint
        run: ./lint-c

      - name: Run signer static analysis
        id: signerStaticAnalysis
        run: |
          ./static-analysis-signer
          echo '### Static analysis found no errors' >> $GITHUB_STEP_SUMMARY

      - name: Add static analysis summary
        run: |
          cat $(find -name index.html) | sed '/<head>/,/<\/head>/{/<head>/b;/<\/head>/b;d;}' >> $GITHUB_STEP_SUMMARY
        if: always() && steps.signerStaticAnalysis.outcome == 'failure'
