name: Signer static analysis

on: [push]

jobs:
  run-static-analysis:
    name: Run static analysis
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Build the ledger docker image
        run: docker/ledger/build

      - name: Run static analysis
        run: |
          mkdir -p static-analysis
          ./static-analysis-signer > static-analysis/signer.xml

      - name: Upload static analysis results
        uses: actions/upload-artifact@v3
        with:
          name: signer-static-analysis
          path: static-analysis/signer.xml

      - name: Write to Job Summary
        if: always()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const xml2js = require('xml2js');
            const parser = new xml2js.Parser();
            const xml = fs.readFileSync('static-analysis/signer.xml');
            parser.parseString(xml, (err, result) => {
              if (err) {
                core.setFailed(err.message);
                return;
              }
              const summary = result.cppcheck.results[0].error.length;
              core.setOutput('summary', summary);
            });
