name: Run unit tests

on:
  workflow_call:
    inputs:
      powhsm-ref:
        description: 'Branch or tag name to test for rsk-powhsm repo'
        type: string
        required: false
        default: 'develop-2.3'

jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.powhsm-ref }}

      - name: Build the middleware docker image
        run: docker/mware/build
        shell: bash

      - name: Middleware tests
        run: middleware/test-all
        shell: bash

      - name: Ledger tests for TCPSigner
        run: ledger/test/test-all
        shell: bash

      - name: Ledger Signer's tests
        working-directory: ledger/src/signer/test/
        run: |
          for d in difficulty sha256 srlp; do
            (cd "$d" && make clean test)
          done
        shell: bash

      - name: Ledger common lib tests
        working-directory: ledger/src/common/test/
        run: |
          for d in memutil; do
            (cd "$d" && make clean test)
          done
        shell: bash
